spring.datasource.url=jdbc:mysql://tagndb-tagn.g.aivencloud.com:21082/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_LHEehgUKClDgZOLRwmn
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect